### ISSUE TITLE
corrupted irrr_models.tar.gz file?

### ISSUE THREAD

**Issue by marygee** [beerqa/IRRR#3]
I have tried to download and extract the irrr_models.tar.gz file multiple times now, and during extraction of the model.ckpt.data-00000-of-00001 file I get:
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive

Could the file possible be corrupted?

**Comment by qipeng** [comment]
Thanks for the feedback! I have replaced the file in the server, could you try downloading it from the same link again?

**Comment by marygee** [comment]
Tried now, and it seems to work as it should! Thanks a lot.
